'use client'

import { useEffect, useState } from 'react'
import { getToken, getUser } from '@/lib/engine'
import { FileText, Copy, Check, Search, ChevronDown, ChevronUp, Download, Printer, Trash2, Filter } from 'lucide-react'

interface NoteRecord {
  id: string
  data: {
    userId?: string
    clientName?: string
    reportType?: string
    generatedNote?: string
    rawInput?: string
    workerName?: string
    duration?: string
    date?: string
  }
  createdAt: string
}

const ENGINE_URL = process.env.NEXT_PUBLIC_ENGINE_URL ?? 'https://saas-engine-production.up.railway.app'

function exportTxt(note: NoteRecord) {
  const header = [
    `NoteScribe AI — ${note.data.reportType ?? 'Note'}`,
    `Participant: ${note.data.clientName ?? '—'}`,
    `Worker:      ${note.data.workerName ?? '—'}`,
    `Date:        ${note.data.date ?? new Date(note.createdAt).toLocaleDateString('en-AU')}`,
    `Duration:    ${note.data.duration ?? '—'}`,
    '─'.repeat(56),
    '',
  ].join('\n')
  const blob = new Blob([header + (note.data.generatedNote ?? '')], { type: 'text/plain;charset=utf-8' })
  const url  = URL.createObjectURL(blob)
  const a    = document.createElement('a')
  a.href     = url
  a.download = `${(note.data.clientName ?? 'note').replace(/\s+/g, '-')}-${note.data.date ?? 'note'}.txt`
  a.click()
  URL.revokeObjectURL(url)
}

function printNote(note: NoteRecord) {
  const win = window.open('', '_blank')
  if (!win) return
  win.document.write(`
    <html><head>
      <title>${note.data.reportType} — ${note.data.clientName}</title>
      <style>
        body { font-family: Georgia, serif; max-width: 700px; margin: 40px auto; color: #1a1a1a; font-size: 13px; line-height: 1.7; }
        h1   { font-size: 18px; font-weight: bold; margin-bottom: 4px; }
        .meta { color: #666; font-size: 12px; margin-bottom: 24px; border-bottom: 1px solid #e5e5e5; padding-bottom: 12px; }
        p    { margin: 0 0 14px; white-space: pre-wrap; }
        @media print { body { margin: 20mm; } }
      </style>
    </head><body>
      <h1>${note.data.reportType ?? 'NDIS Note'}</h1>
      <div class="meta">
        Participant: <strong>${note.data.clientName ?? '—'}</strong> &nbsp;·&nbsp;
        Worker: ${note.data.workerName ?? '—'} &nbsp;·&nbsp;
        Date: ${note.data.date ?? new Date(note.createdAt).toLocaleDateString('en-AU')}
        ${note.data.duration ? ` &nbsp;·&nbsp; Duration: ${note.data.duration}` : ''}
      </div>
      ${(note.data.generatedNote ?? '').split('\n\n').map(p => `<p>${p.replace(/\n/g, '<br>')}</p>`).join('')}
      <div style="margin-top:32px;color:#999;font-size:11px;border-top:1px solid #eee;padding-top:8px;">Generated by NoteScribe AI · notescribe.ai</div>
    </body></html>
  `)
  win.document.close()
  win.print()
}

export default function HistoryPage() {
  const [notes, setNotes]       = useState<NoteRecord[]>([])
  const [loading, setLoading]   = useState(true)
  const [search, setSearch]     = useState('')
  const [typeFilter, setType]   = useState('All')
  const [expanded, setExpanded] = useState<string | null>(null)
  const [copied, setCopied]     = useState<string | null>(null)
  const [deleting, setDeleting] = useState<string | null>(null)

  useEffect(() => {
    const token = getToken()
    const user  = getUser()
    if (!token) return
    fetch(`${ENGINE_URL}/api/orgs/${process.env.NEXT_PUBLIC_ORG_ID}/projects/${process.env.NEXT_PUBLIC_PROJECT_ID}/records?entityType=ndis_note&limit=200`, {
      headers: { 'X-API-Key': process.env.NEXT_PUBLIC_API_KEY ?? '' },
    })
      .then(r => r.json())
      .then(d => {
        const all: NoteRecord[] = d.data?.data ?? []
        // show only current user's notes
        const mine = user?.id ? all.filter(n => n.data.userId === user.id || !n.data.userId) : all
        setNotes(mine.sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()))
      })
      .catch(() => {})
      .finally(() => setLoading(false))
  }, [])

  const allTypes  = ['All', ...Array.from(new Set(notes.map(n => n.data.reportType).filter(Boolean) as string[]))]

  const filtered = notes.filter(n => {
    const q = search.toLowerCase()
    const matchSearch =
      n.data.clientName?.toLowerCase().includes(q) ||
      n.data.reportType?.toLowerCase().includes(q) ||
      n.data.generatedNote?.toLowerCase().includes(q)
    const matchType = typeFilter === 'All' || n.data.reportType === typeFilter
    return matchSearch && matchType
  })

  async function copy(id: string, text: string) {
    await navigator.clipboard.writeText(text)
    setCopied(id)
    setTimeout(() => setCopied(null), 2000)
  }

  async function deleteNote(id: string) {
    setDeleting(id)
    try {
      await fetch(`${ENGINE_URL}/api/orgs/${process.env.NEXT_PUBLIC_ORG_ID}/projects/${process.env.NEXT_PUBLIC_PROJECT_ID}/records/${id}`, {
        method: 'DELETE',
        headers: { 'X-API-Key': process.env.NEXT_PUBLIC_API_KEY ?? '' },
      })
      setNotes(prev => prev.filter(n => n.id !== id))
    } catch { /* silent */ }
    setDeleting(null)
  }

  return (
    <div className="space-y-5">
      <div className="flex items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Note History</h1>
          <p className="text-gray-500 text-sm mt-0.5">All your generated NDIS notes</p>
        </div>
        <span className="text-sm text-gray-400 font-medium">{notes.length} notes</span>
      </div>

      {/* Search + filter row */}
      <div className="flex gap-3 flex-wrap">
        <div className="relative flex-1 min-w-[200px]">
          <Search className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
          <input
            type="text" value={search} onChange={e => setSearch(e.target.value)}
            placeholder="Search participant, note content…"
            className="w-full pl-10 pr-4 py-2.5 border border-gray-200 rounded-xl text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-emerald-500 text-sm bg-white"
          />
        </div>
        <div className="relative">
          <Filter className="absolute left-3 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-gray-400" />
          <select value={typeFilter} onChange={e => setType(e.target.value)}
            className="pl-8 pr-8 py-2.5 border border-gray-200 rounded-xl text-gray-900 focus:outline-none focus:ring-2 focus:ring-emerald-500 text-sm bg-white appearance-none cursor-pointer">
            {allTypes.map(t => <option key={t} value={t}>{t}</option>)}
          </select>
        </div>
      </div>

      {loading && (
        <div className="flex items-center justify-center py-16">
          <div className="w-8 h-8 border-2 border-emerald-600 border-t-transparent rounded-full animate-spin" />
        </div>
      )}

      {!loading && filtered.length === 0 && (
        <div className="text-center py-16">
          <div className="w-14 h-14 bg-emerald-50 rounded-2xl flex items-center justify-center mx-auto mb-4">
            <FileText className="w-7 h-7 text-emerald-300" />
          </div>
          <p className="text-gray-500 font-medium">{notes.length === 0 ? 'No notes yet' : 'No matching notes'}</p>
          <p className="text-gray-400 text-sm mt-1">
            {notes.length === 0 ? 'Generate your first note from the Write Note tab.' : 'Try a different search or filter.'}
          </p>
        </div>
      )}

      <div className="space-y-3">
        {filtered.map(note => (
          <div key={note.id} className="bg-white rounded-2xl border border-gray-200 shadow-sm overflow-hidden">
            <div
              className="flex items-center justify-between px-5 py-4 cursor-pointer hover:bg-gray-50 transition-colors"
              onClick={() => setExpanded(expanded === note.id ? null : note.id)}
            >
              <div className="flex items-center gap-3 min-w-0">
                <div className="w-9 h-9 bg-emerald-100 rounded-xl flex items-center justify-center flex-shrink-0">
                  <FileText className="w-4 h-4 text-emerald-600" />
                </div>
                <div className="min-w-0">
                  <p className="font-semibold text-gray-900 text-sm truncate">
                    {note.data.clientName || 'Unknown participant'} — {note.data.reportType || 'Note'}
                  </p>
                  <p className="text-xs text-gray-400 mt-0.5">
                    {note.data.date || new Date(note.createdAt).toLocaleDateString('en-AU')}
                    {note.data.duration ? ` · ${note.data.duration}` : ''}
                    {note.data.workerName ? ` · ${note.data.workerName}` : ''}
                  </p>
                </div>
              </div>
              <div className="flex items-center gap-1 flex-shrink-0 ml-3" onClick={e => e.stopPropagation()}>
                <button onClick={() => copy(note.id, note.data.generatedNote ?? '')}
                  className="p-1.5 text-gray-400 hover:text-emerald-600 rounded-lg hover:bg-emerald-50 transition-colors" title="Copy">
                  {copied === note.id ? <Check className="w-4 h-4 text-green-500" /> : <Copy className="w-4 h-4" />}
                </button>
                <button onClick={() => exportTxt(note)}
                  className="p-1.5 text-gray-400 hover:text-emerald-600 rounded-lg hover:bg-emerald-50 transition-colors" title="Download .txt">
                  <Download className="w-4 h-4" />
                </button>
                <button onClick={() => printNote(note)}
                  className="p-1.5 text-gray-400 hover:text-emerald-600 rounded-lg hover:bg-emerald-50 transition-colors" title="Print / Save PDF">
                  <Printer className="w-4 h-4" />
                </button>
                <button onClick={() => { if (confirm('Delete this note?')) deleteNote(note.id) }}
                  disabled={deleting === note.id}
                  className="p-1.5 text-gray-400 hover:text-red-500 rounded-lg hover:bg-red-50 transition-colors" title="Delete">
                  <Trash2 className="w-4 h-4" />
                </button>
                {expanded === note.id ? <ChevronUp className="w-4 h-4 text-gray-400 ml-1" /> : <ChevronDown className="w-4 h-4 text-gray-400 ml-1" />}
              </div>
            </div>
            {expanded === note.id && (
              <div className="px-5 pb-5 border-t border-gray-100 pt-4">
                <p className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-2">Generated note</p>
                <div className="bg-emerald-50 rounded-xl p-4 text-gray-700 text-sm leading-relaxed whitespace-pre-wrap border border-emerald-100">
                  {note.data.generatedNote}
                </div>
                {note.data.rawInput && (
                  <>
                    <p className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-2 mt-4">Original notes</p>
                    <div className="bg-gray-50 rounded-xl p-3 text-gray-500 text-xs italic border border-gray-200">
                      {note.data.rawInput}
                    </div>
                  </>
                )}
                <div className="flex gap-3 mt-4">
                  <button onClick={() => exportTxt(note)}
                    className="flex items-center gap-1.5 text-xs font-semibold text-emerald-700 bg-emerald-50 border border-emerald-200 px-3 py-2 rounded-lg hover:bg-emerald-100 transition-colors">
                    <Download className="w-3.5 h-3.5" /> Download .txt
                  </button>
                  <button onClick={() => printNote(note)}
                    className="flex items-center gap-1.5 text-xs font-semibold text-gray-700 bg-gray-50 border border-gray-200 px-3 py-2 rounded-lg hover:bg-gray-100 transition-colors">
                    <Printer className="w-3.5 h-3.5" /> Print / Save PDF
                  </button>
                </div>
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  )
}
